config/routes.rb
Rails.application.routes.draw do
  # Global Resources
  resources :courses
  resources :students
  resources :classrooms

  # RootRoute main LandingPage
  # root to: 'report#index'
  root to: 'courses#index'
end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
  # Relations
  belongs_to :course
  belongs_to :student

  # Rails validations
  validates_presence_of :entry_at, on: [:create, :update]
  validates_presence_of :course_id, on: [:create, :update]
  validates_presence_of :student_id, on: [:create, :update]

  # Setup attributes
  before_validation :setup

  private
    # Setup attributes which are dynamic
    def setup
      self.entry_at = Time.now
    end
end

app/models/course.rb
class Course < ActiveRecord::Base
  # Relations
  has_many :classrooms, dependent: :destroy
  has_many :students, through: :classrooms

  # EnumerateIt
  extend EnumerateIt
  has_enumeration_for :status, with: Status

  # Rails validations
  validates :name, length: { maximum: 45 }, presence: true, on: [:create, :update]
  validates :description, length: { maximum: 45 }, presence: true, on: [:create, :update]
  validates :status, numericality: true, inclusion: { in: 0..10 }, presence: true, on: [:create, :update]
end

app/models/student.rb
class Student < ActiveRecord::Base
  # Relations
  has_many :classrooms, dependent: :destroy
  has_many :courses, through: :classrooms

  # EnumerateIt
  extend EnumerateIt
  has_enumeration_for :status, with: Status

  # Rails validations
  validates :name, length: { maximum: 45 }, presence: true, on: [:create, :update]
  validates :register_number, length: { maximum: 45 }, presence: true, on: [:create, :update]
  validates :status, numericality: true, inclusion: { in: 0..10 }, presence: true, on: [:create, :update]
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController
  before_action :set_nested, only: [:create, :update]
  before_action :set_select_objs, only: [:new, :create, :edit, :update]
  before_action :set_classroom, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @classrooms = Classroom.all
    respond_with(@classrooms)
  end

  # def show
  #   respond_with(@classroom)
  # end

  def new
    @classroom = Classroom.new
    respond_with(@classroom)
  end

  def edit
  end

  # TODO accepts_nested_attributres_for
  def create
    if @course.nil? || @students.empty?
      @classroom = Classroom.new(course: @course, student: @student_ids.first)
      @classroom.save
      respond_with(@classroom)
    else
      @student_ids.each do |s|
        @course.classrooms << Classroom.new(student_id: s.last)
      end

      @course.save
      respond_with(@classroom = @course.classrooms.first, location: classrooms_path)
    end
  end

  def update
    if @course.nil?
      respond_with(@classroom)
    else
      @student_ids.each do |s|
        @course.classrooms << Student.where(id: s).take
      end
    end

    @course.save
    respond_with(@classroom, location: classrooms_path)
  end

  def destroy
    @classroom.destroy
    respond_with(@classroom)
  end

  private
    def set_classroom
      @classroom = Classroom.find(params[:id])
    end

    def set_select_objs
      @courses = Course.all
      @students = Student.all
    end

    def classroom_params
      base_params = params.require(:classroom).permit(:course_id)
    end

    def set_nested
      @course = Course.where(id: params[:classroom][:course_id]).take

      # Fixing view framework bug for checkbox (it framework duplicate the checkboxes)
      @student_ids = params[:classroom][:student_id]
      @student_ids = [@student_ids] if @student_ids.is_a?String
      @student_ids = @student_ids.to_a unless @student_ids.is_a?Array
    end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @courses = Course.all
    respond_with(@courses)
  end

  # def show
  #   respond_with(@course)
  # end

  def new
    @course = Course.new
    respond_with(@course)
  end

  def edit
  end

  def create
    @course = Course.new(course_params)
    @course.save
    respond_with(@course, location: courses_path)
  end

  def update
    @course.update(course_params)
    respond_with(@course, location: courses_path)
  end

  def destroy
    @course.destroy
    respond_with(@course)
  end

  private
    def set_course
      @course = Course.find(params[:id])
    end

    def course_params
      params.require(:course).permit(:name, :description, :status)
    end
end

app/controllers/report_controller.rb
class ReportController < ApplicationController
  def index
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @students = Student.all
    respond_with(@students)
  end

  # def show
  #   respond_with(@student)
  # end

  def new
    @student = Student.new
    respond_with(@student)
  end

  def edit
  end

  def create
    @student = Student.new(student_params)
    @student.save
    respond_with(@student, location: students_path)
  end

  def update
    @student.update(student_params)
    respond_with(@student, location: students_path)
  end

  def destroy
    @student.destroy
    respond_with(@student)
  end

  private
    def set_student
      @student = Student.find(params[:id])
    end

    def student_params
      params.require(:student).permit(:name, :register_number, :status)
    end
end

app/helpers/actions_helper.rb
module ActionsHelper
  def current_controller_path?(controller_sym)
    params[:controller] == controller_sym.to_s ? 'active' : ''
  end

  def back_action
    self.send("#{params[:controller]}_path")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/report_helper.rb
module ReportHelper
end

app/helpers/sidebar_helper.rb
module SidebarHelper
  def current_controller_path?(controller_sym)
    params[:controller] == controller_sym.to_s ? 'active' : ''
  end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/classrooms/_form.html.slim
= form_for @classroom do |f|
  - if @classroom.errors.any?
    .alert.alert-danger
      h2 = "#{pluralize(@classroom.errors.count, "error")} prohibited this classroom from being saved:"
      ul
        - @classroom.errors.full_messages.each do |message|
          li = message

  .row
    .col-md-12
      .form-group
        = f.label :course
        = f.collection_select(:course_id, @courses, :id, :name, options={prompt: true}, html={class: 'form-control', required: true})

  .row
    .card.no-shawdow
      .header
        h4.title Selecione os Estudantes
      .content
        .row
          .col-md-12
            ul class="in-line-list list-unstyled team-members"
              -@students.each_with_index do |student, i|
                li.col-md-3
                  .col-xs-4
                    .avatar
                      =image_tag 'profile.jpg'
                  .col-xs-4
                    =student.name
                    .text-muted =student.status
                  .col-xs-3
                    .checkbox
                      input id="classroom_student_#{i}" type="checkbox" name="classroom[student_id][#{i}]" value="#{student.id}"

  .row
    .col-md-4.col-md-offset-2
      = link_to 'Voltar', back_action, class: 'btn btn-info btn-wd'
    .col-md-4
      .actions = f.submit class: 'btn btn-success btn-wd'

app/views/classrooms/edit.html.slim
.row
  .col-md-12
    .card
      .header
        h4.title = t('actions.classrooms.edit')
      .content
        = render 'form'

app/views/classrooms/index.html.slim
.row
  .col-md-12
    .card
      .header
        a.btn.btn-info.btn-wd.right href="#{new_classroom_path}" =t('actions.classrooms.new')
        h4.title Lista de Turmas
        p.category Associe quantos alunos quiser a cada Turma
      .content.table-responsive.table-full-width
        table.table.table-striped
          thead
            tr
              th =t('activerecord.attributes.classroom.course')
              th =t('activerecord.attributes.classroom.student')
              th =t('activerecord.attributes.classroom.entry_at')
              th
              th
          tbody
            - @classrooms.each do |classroom|
              tr
                td =classroom.course.name
                td =classroom.student.name
                td =l classroom.entry_at, format: :long
                td
                  =link_to edit_classroom_path(classroom) do
                    i.ti-pencil-alt
                td
                  =link_to classroom, data: {:confirm => 'Você tem certeza?'}, method: :delete, class: 'text-danger' do
                    i.ti-trash

app/views/classrooms/new.html.slim
.row
  .col-md-12
    .card
      .header
        h4.title = t('actions.classrooms.new')
      .content
        = render 'form'

app/views/classrooms/show.html.slim
p#notice = notice

p
  strong Student:
  = @classroom.student
p
  strong Course:
  = @classroom.course
p
  strong Entry at:
  = @classroom.entry_at

= link_to 'Edit', edit_classroom_path(@classroom)
'|
= link_to 'Back', classrooms_path

app/views/courses/_form.html.slim
= form_for @course do |f|
  - if @course.errors.any?
    .alert.alert-danger
      h2 = "#{pluralize(@course.errors.count, "error")} prohibited this course from being saved:"
      ul
        - @course.errors.full_messages.each do |message|
          li = message

  .row
    .col-md-12
      .form-group
        = f.label :name
        = f.text_field :name, class: 'form-control border-input', required: true

  .row
    .col-md-12
      .form-group
        = f.label :description
        = f.text_area :description, class: 'form-control border-input', required: true

  .actions = f.submit class: 'right btn btn-success btn-wd'
  = link_to 'Voltar', courses_path, class: 'left btn btn-info btn-wd'

  .row
    .col-md-offset-3.col-md-2
      .checkbox
        = f.check_box :status
        = f.label :status

app/views/courses/edit.html.slim
.row
  .col-md-12
    .card
      .header
        h4.title = t('actions.courses.edit')
      .content
        = render 'form'

app/views/courses/index.html.slim
.row
  .col-md-12
    .card
      .header
        a.btn.btn-info.btn-wd.right href="#{new_course_path}" =t('actions.courses.new')
        h4.title =t('actions.courses.index')
        p.category Acesse o link Turmas para Associar Alunos ao Curso
      .content.table-responsive.table-full-width
        table.table.table-striped
          thead
            tr
              th
              th =t('activerecord.attributes.course.name')
              th =t('activerecord.attributes.course.description')
              th =t('activerecord.attributes.course.status')
              /th
              th
              th
          tbody
            - @courses.each do |course|
              tr
                td
                td =course.name
                td =course.description
                td =course.status_humanize
                /td =link_to 'Visualizar', course
                td =link_to 'Editar', edit_course_path(course)
                td =link_to 'Deletar', course, data: {:confirm => 'Você tem certeza?'}, :method => :delete

app/views/courses/new.html.slim
.row
  .col-md-12
    .card
      .header
        h4.title = t('actions.courses.new')
      .content
        = render 'form'

app/views/courses/show.html.slim
p#notice = notice

p
  strong Name:
  = @course.name
p
  strong Description:
  = @course.description
p
  strong Status:
  = @course.status

= link_to 'Edit', edit_course_path(@course)
'|
= link_to 'Back', courses_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title RHIS O melhor Gerenciador de Turmas
    link href="https://fonts.googleapis.com/css?family=Muli:400,300" rel="stylesheet" type="text/css"
    =stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    =csrf_meta_tags
  body
    .wrapper
      = render 'layouts/partials/sidebar'

      .main-panel
        = render 'layouts/partials/nav_bar'

        .content
          .container-fluid
            = yield

    =javascript_include_tag 'application', 'data-turbolinks-track' => true

app/views/layouts/partials/_nav_bar.html.slim
nav.navbar.navbar-default
  .container-fluid
    .navbar-header
      button.navbar-toggle type="button"
        span.sr-only Toggle navigation
        span.icon-bar.bar1
        span.icon-bar.bar2
        span.icon-bar.bar3
      a.navbar-brand href="#" =t("controllers.#{params[:controller]}")

    /.collapse.navbar-collapse
    /  ul.nav.navbar-nav.navbar-right
    /    li
    /      a href="#" class="dropdown-toggle" data-toggle="dropdown"
    /        i class="ti-panel"
    /        p Stats
    /    li.dropdown
    /      a href="#" class="dropdown-toggle" data-toggle="dropdown"
    /        i class="ti-bell"
    /        p class="notification" 5
    /        p Notifications
    /        b.caret
    /      ul.dropdown-menu
    /        li: a href="#" Notification 1
    /        li: a href="#" Notification 2
    /        li: a href="#" Notification 3
    /        li: a href="#" Notification 4
    /        li: a href="#" Another notification
    /    li
    /      a href="#"
    /        i.ti-settings
    /        p Settings

app/views/layouts/partials/_sidebar.html.slim
/! sidebar
.sidebar data-color="purple" data-image="/light-bootstrap-dashboard/assets/img/sidebar-5.jpg"
  .sidebar-wrapper
    .logo
      a.simple-text href="#" RHIS Aulas
    ul.nav
      /li class="#{current_controller_path?(:report)}"
      /  =link_to root_path
      /    i.ti-pie-chart
      /    p = t('controllers.report')

      li class="#{current_controller_path?(:courses)}"
        =link_to courses_path
          i.ti-bookmark-alt
          p = t('controllers.courses')

      li class="#{current_controller_path?(:students)}"
        =link_to students_path
          i.ti-user
          p = t('controllers.students')

      li class="#{current_controller_path?(:classrooms)}"
        =link_to classrooms_path
          i.ti-view-list-alt
          p = t('controllers.classrooms')

app/views/report/index.html.slim
.row
  .col-lg-3.col-sm-6
    =render 'report/partials/capacity_card'
  .col-lg-3.col-sm-6
    =render 'report/partials/revenue_card'
  .col-lg-3.col-sm-6
    =render 'report/partials/error_card'
  .col-lg-3.col-sm-6
    =render 'report/partials/twitter_card'

app/views/report/partials/_area_chart.html.slim
.card
  .header
    h4.title Users Behavior
    p.category 24 Hours performance
  .content
    #chartHours.ct-chart
    .footer
      .chart-legend
        i class="fa fa-circle text-info"
        | Open
        i class="fa fa-circle text-danger"
        | Click
        i class="fa fa-circle text-warning"
        | Click Second Time
      hr
      .stats
        i.ti-reload
        | Updated 3 minutes ago

app/views/report/partials/_capacity_card.html.slim
div class="card"
  div class="content"
    div class="row"
      div class="col-xs-5"
        div class="icon-big icon-warning text-center"
          i class="ti-server"
      div class="col-xs-7"
        div class="numbers"
          p Capacity
          | 105GB
    div class="footer"
      hr
      div class="stats"
        i class="ti-reload"
        | Updated now

app/views/report/partials/_error_card.html.slim
div class="card"
  div class="content"
    div class="row"
      div class="col-xs-5"
        div class="icon-big icon-danger text-center"
          i class="ti-pulse"
      div class="col-xs-7"
        div class="numbers"
          p Errors
          | 32
    div class="footer"
      hr
      div class="stats"
        i class="ti-timer"
        | In the last hour

app/views/report/partials/_line_chart.html.slim
.card
  .header
    h4.title 2015 Sales
    p.category All products including Taxes
  .content
    #chartActivity.ct-chart
    .footer
      .chart-legend
        i class="fa fa-circle text-info"
        | Tesla Model S
        i class="fa fa-circle text-warning"
        | BMW 5 Series
      hr
      .stats
        i.ti-check
        | Data information certified

app/views/report/partials/_pie_chart.html.slim
.card
  .header
    h4.title Email Statistics
    p.category Last Campaign Performance
  .content
    #chartPreferences.ct-chart.ct-perfect-fourth
    .footer
      .chart-legend
        i class="fa fa-circle text-info"
        | Open
        i class="fa fa-circle text-danger"
        | Bounce
        i class="fa fa-circle text-warning"
        | Unsubscribe
      hr
      .stats
        i.ti-timer
        | Campaign sent 2 days ago

app/views/report/partials/_revenue_card.html.slim
div class="card"
  div class="content"
    div class="row"
      div class="col-xs-5"
        div class="icon-big icon-success text-center"
          i class="ti-wallet"
      div class="col-xs-7"
        div class="numbers"
          p Revenue
          | $1,345
    div class="footer"
      hr
      div class="stats"
        i class="ti-calendar"
        | Last day

app/views/report/partials/_twitter_card.html.slim
div class="card"
  div class="content"
    div class="row"
      div class="col-xs-5"
        div class="icon-big icon-info text-center"
          i class="ti-twitter-alt"
      div class="col-xs-7"
        div class="numbers"
          p Followers
          | +45
    div class="footer"
      hr
      div class="stats"
        i class="ti-reload"
        | Updated now

app/views/students/_form.html.slim
= form_for @student do |f|
  - if @student.errors.any?
    .alert.alert-danger
      h2 = "#{pluralize(@student.errors.count, "error")} prohibited this student from being saved:"
      ul
        - @student.errors.full_messages.each do |message|
          li = message

  .row
    .col-md-12
      .form-group
        = f.label :name
        = f.text_field :name, class: 'form-control border-input', required: true

  .row
    .col-md-12
      .form-group
        = f.label :register_number
        = f.text_field :register_number, class: 'form-control border-input numeric', required: true

  .actions = f.submit class: 'right btn btn-success btn-wd'
  = link_to 'Voltar', back_action, class: 'left btn btn-info btn-wd'

  .row
    .col-md-offset-3.col-md-2
      .checkbox
        = f.check_box :status
        = f.label :status

app/views/students/edit.html.slim
.row
  .col-md-12
    .card
      .header
        h4.title = t('actions.students.edit')
      .content
        = render 'form'

app/views/students/index.html.slim
.row
  .col-md-12
    .card
      .header
        a.btn.btn-info.btn-wd.right href="#{new_student_path}" =t('actions.students.new')
        h4.title =t('actions.students.index')
        p.category Acesse o link Turmas para Associar Alunos à Cursos
      .content.table-responsive.table-full-width
        table.table.table-striped
          thead
            tr
              th
              th =t('activerecord.attributes.student.name')
              th =t('activerecord.attributes.student.register_number')
              th =t('activerecord.attributes.student.status')
              /th
              th
              th

          tbody
            - @students.each do |student|
              tr
                td
                td =student.name
                td =student.register_number
                td =student.status_humanize
                /td
                /  =link_to student do
                /    i.ti-eye
                td
                  =link_to edit_student_path(student) do
                    i.ti-pencil-alt
                td
                  =link_to student, data: {:confirm => 'Você tem certeza?'}, method: :delete, class: 'text-danger' do
                    i.ti-trash

app/views/students/new.html.slim
.row
  .col-md-12
    .card
      .header
        h4.title = t('actions.students.new')
      .content
        = render 'form'

app/views/students/show.html.slim
p#notice = notice

p
  strong Name:
  = @student.name
p
  strong Register number:
  = @student.register_number
p
  strong Status:
  = @student.status

= link_to 'Edit', edit_student_path(@student)
'|
= link_to 'Back', students_path